<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-02-11 11:02

$extensionPath = t3lib_extMgm::extPath('ren_documents');
return array(
	'tx_rendocuments_alert' => $extensionPath . 'lib/class.tx_rendocuments_alert.php',
	'tx_rendocuments_dynflex' => $extensionPath . 'lib/class.tx_rendocuments_dynflex.php',
	'tx_rendocuments_filecontrol' => $extensionPath . 'lib/class.tx_rendocuments_filecontrol.php',
	'tx_rendocuments_filehelper' => $extensionPath . 'lib/class.tx_rendocuments_filehelper.php',
	'tx_rendocuments_filemanager' => $extensionPath . 'lib/class.tx_rendocuments_filemanager.php',
	'tx_rendocuments_recordlist' => $extensionPath . 'lib/class.tx_rendocuments_recordlist.php',
	'tx_rendocuments_sysfolder' => $extensionPath . 'lib/class.tx_rendocuments_sysfolder.php',
	'tx_rendocuments_tcahelper' => $extensionPath . 'lib/class.tx_rendocuments_tcahelper.php',
	'tx_rendocuments_tcedummy' => $extensionPath . 'lib/class.tx_rendocuments_tcedummy.php',
	'tx_rendocuments_module1' => $extensionPath . 'mod1/index.php',
	'tx_rendocuments_navframe' => $extensionPath . 'mod1/tx_rendocuments_navframe.php',
	'tx_rendocuments_pi1' => $extensionPath . 'pi1/class.tx_rendocuments_pi1.php',
	'tx_rendocuments_pi1_wizicon' => $extensionPath . 'pi1/class.tx_rendocuments_pi1_wizicon.php',
);
?>